// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXzSczylAAYTwztpgIuLc3Kcvd8QC2VI0',
    appId: '1:911038445881:web:ac44b3fc6a0fbd958550e8',
    messagingSenderId: '911038445881',
    projectId: 'isf-7bbaa',
    authDomain: 'isf-7bbaa.firebaseapp.com',
    storageBucket: 'isf-7bbaa.appspot.com',
    measurementId: 'G-NK3GSVHB88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkOo11YLnUtZGZLox4Tf7DL15bYtlydbE',
    appId: '1:911038445881:android:1b8ac7b871187a3b8550e8',
    messagingSenderId: '911038445881',
    projectId: 'isf-7bbaa',
    storageBucket: 'isf-7bbaa.appspot.com',
  );
}
